version: "3"
services:
  react-app:
    build:
      context: ./client
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client
    depends_on:
      - express-app

  express-app:
    build:
      context: ./express
    ports:
      - "3001:3001"
    # volumes:
    # - ./express
